#!/bin/sh

# cleanup

rm -rf obj_dir
rm -f cpu.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace cpu.sv part2_top.sv ALU.sv Reg_file.sv instrMem.sv controlUnit.sv signExtend.sv PC_REG.sv --exe cpu_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcpu.mk Vcpu

# run executable simulation file
obj_dir/Vcpu

# run by typing:
# source ./doit.sh
