#!/bin/sh

# cleanup

rm -rf obj_dir
rm -f cpu_v2.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace cpu_v2.sv dataMemory.sv part2_top.sv ALU.sv Reg_file.sv instrMem.sv controlUnit.sv signExtend.sv PC_REG.sv --exe cpu_v2_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcpu_v2.mk Vcpu_v2

# run executable simulation file
obj_dir/Vcpu_v2

# run by typing:
# source ./doit.sh
